export const DRUG_NAMES = {
  'Asava and Arista': ['Drākşāsav', 'Punarnavādyarişta', 'Babbűlarista'],
  'Arka': ['Pudinārka', 'Yavanyārka'],
  'Avaleha and Pāka': ['Aştāngāvaleha', 'Ardrakakhanda avalaha', 'Eranda Päka', 'Kalyāņāvaleha', 'Pūgakhanda (Aparah)', 'Vyāghri Haritaki', 'S ri Bahusálo guda'],
  "Kvātha Cũrņa":['Angamardaprasamana Kaşāya Cūrņa', 'Arkādi Kvātha Cũrņa', 'Asmarihara Kaşāya Cũrņa', 'Kutajāştaka Kvätha Cũrņa', 'Krmighna Kaşāya Cũrņa', 'Guducyādi Kvātha Cũrņa', 'Gojihvādi Kvātha Cũrņa', 'Trnaparicamula Kvātha Cũrņa', 'Triphala Kvatha Cũrņa', 'Triphala Kasaya Cũrņa', 'Därvyādi Kvatha Cũrņa', 'Devadārvādi Kvätha Cũrņa', 'Dhanyapancaka Kvätha Cũrņa', 'Nimbādi Kvätha Cũrņa', 'Pathyädi Kvätha (Sadanga) Cũrņa', 'Phalatrikädi Kvätha Cũrņa', 'Māşabalādi Kvatha Cũrņa', 'Műtravirecaniya Kvätha Cũrņa', 'Mūtrasangrahaniya Kvatha Cũrņa', 'Rāsnāsaptaka Kvätha Cũrņa', 'Vatsakādi Kvātha Cũrņa', 'Varunādi Kvātha Cũrņa', 'Śvāsahara Kaşāya Cũrņa', 'Stanyajanana Kaşāya Cũrņa', 'Stanya Sodhana Kaşaya Cũrņa'],
  "Guggulu":['Pancāmṛta-Lauha Guggulu', 'Punarnavā Guggulu'],
  "Ghrta":['Arjuna Ghrta', 'Brhat Asvagandhā Ghrta', 'Brhacchāgalādya Ghrta', 'Satāvaryādi Ghrta'],
  "Cūrņa":['Agnimukha Cúrna', 'Asvagandhādi Cũrņa', 'Astangalavana Cũrņa',  'Katphalādi Cũrņa', 'Gandhaka Rasayana', 'Dasanasamskāra Cũrņa', 'Dadimäşțaka Cũrņa', 'Nārāca Cũrņa', 'Nāsikā Cũrņa', 'Paricakola Cũrņa', 'Pañcanimba Cũrņa', 'Palasabījādi Cũrņa', 'Musali Cũrņa', 'Laghugangadhara Cũrņa', 'Laghulãi Cũrņa', 'Lavangădi Cũrņa', 'Vidangadi Cũrņa', 'Samasarkarā Cũrņa', 'Sarasvata Cũrņa'],
  "Taila":['Apāmārga kṣāra Taila', 'Aśvagandha Taila', 'Kubjaprāsārani Taila', 'Kşāra Taila', 'Gudūcyādi Taila', 'Dasamüla Taila', 'Pañcaguņa Taila', 'Pippalyādi Taila', 'Brhanmaricādya Taila', 'Madhyamanārāyaņa Taila', 'Maricādya Taila', 'Mahālākṣādi Taila', 'Műşikādya Taila', 'Väyucchaya surendra Taila', 'Vişnu Taila', 'Vyāghri Taila','Śambūkādya Taila', 'Hingvädi Taila'],
  "Lepa":['Asthisandhānaka Lepa', 'Gandhakādy-amalahara', 'Pāradādi Lepa', 'Vṛddhihara Lepa', 'Sveta Malahama'],
  "Vaţi and Guțikā":['Abhayā Vaţî', 'Arka Vaţî', 'Arsoghnî Vaţî', 'Kutajaghana Vaţî', 'Jvaraghnî Guțika', 'Drākṣādi Guțikā', 'Bolādi Vaţî', 'Bhuvaneśvara Vaţî', 'Mahāśankha Vaţî', 'Mahāgandhaka Vaţî', 'Sarpagandhāghana Vaţî', 'Sarvatobhadra Vaţî', 'Samsamanî Vaţî (gudūcīghana Vaţî)', 'Sukhavirecana Vaţî'],
  "Vartti - Netra Bindu and Añjana":['Nayanāmṛtānjana', 'Nāgārjunārijana'],
  "Parpaţi":['Tamra Parpați', 'Sveta parpați (Kşăra parpaţi)'],
  "Pişti":['Akîka Pişți', 'Jaharamohară Pişti'],
  "Bhasma": ['Akika Bhasma', 'Jaharamoharā Bhasma', 'Sphatikā Bhasma', 'Hajarulayahūda Bhasma', 'Varātikā Bhasma'],
  "Mandūra":['Tārāmandūra guda', 'Triphala Mandūra', 'Sothari Mandūra'],
  "Rasa yoga":['Ajimakanţaka Rasa', 'Arśakuthāra Rasa', 'Amavatāri Rasa', 'Unmādagajakaśari Rasa', 'Kanakasundara Rasa', 'Kastűri Bhairava Rasa', 'Käñcanābhra Rasa', 'Käntavallabha Rasa', 'Kämadudha Rasa (Mukta-yukta)', 'Kālakūța Rasa', 'Kravyāda Rasa', 'Krmikuthāra Rasa', 'Gandamālā kandana Rasa', 'Garbhapāla Rasa', 'Garbhacintāmaņi Rasa', 'Gulmakālānala Rasa', 'Grahaņikapāļa Rasa', 'Candrāmsu Rasa', 'Jalodarāri Rasa', 'Javähara Mohara', 'Jvarāńkuşa Rasa (1)', 'Jvarārikuśa Rasa (II)', 'Tärakeśvara Rasa', 'Trivikrama Rasa', 'Dantodbhedagadāntaka Rasa', 'Nārāca Rasa', 'Nāgārjunābhra Rasa', 'Nityananda Rasa', 'Nidrodaya Rasa', 'Nrpativallabha Rasa', 'Pañcānana Rasa', 'Piyüşavalli Rasa', 'Puspadhanvā Rasa', 'Pürnacandra Rasa', 'Pratapalankeśvara Rasa', 'Pradarāntaka Rasa', 'Pravāla Pañcāmṛta Rasa', 'Bālārka Rasa', 'Brhadagnikumāra Rasa', 'Brhat Pärnacandra Rasa', 'Brhatvangeśvara Rasa', 'Brhat Vidya-dharābhra Rasa', 'Brhacchmgārābhra Rasa', 'Brahmi vați', 'Manamathabhra Rasa', 'Mahājvarāńkuša Rasa', 'Mahätarunärka Rasa', 'Mahāvātavidhvamsana Rasa', 'Manikya Rasa', 'Mehamudgara Rasa', 'Yakūtī', 'Laghu Sütaśekhara Rasa', 'Lila Vilása Rasa', 'Vajrakapāța Rasa', 'Vasantatilaka Rasa', 'Våtagajänkusa Rasa', 'śvāsakāsa Cintamani Rasa', 'Sirah Sülādivajra Rasa', 'Śingārābhra Rasa', 'Śri jayamangala Rasa', 'Śrī rāmābāņa Rasa', 'Sűtaśekhara Rasa', 'Smrtisāgara Rasa', 'Svacchanda Bhairava Rasa', 'Hemagarbha Poţţali Rasa', 'Hemanātha Rasa', 'Hinguleśvara Rasa', 'Hiranyagarbha Pottali Rasa'],
  "Lauha":['Gudúci Lauha', 'Navāyāsa Lauha (Cūrņa)', 'Brhat visama-jvarāntaka Lauha', 'Brhat Sarvajvarahara Lauha', 'Yakṛtplīhāri Lauha', 'Yogarāja', 'Raktapittāntaka Lauha', 'Śatamūlyadi Lauha', 'Šilājitvādi Lauha']
};
